import React from 'react';
export const contractsDetails = () => <div>contracts distinct</div>;
export const contracts_detail_0 = (p:any)=> <div>contracts 0 Article 5</div>;
export const contracts_detail_1 = (p:any)=> <div>contracts 1 Article 7</div>;
export const contracts_detail_2 = (p:any)=> <div>contracts 2 Article 12</div>;
export const contracts_detail_3 = (p:any)=> <div>contracts 3 Appendix A</div>;
export const contracts_detail_4 = (p:any)=> <div>contracts 4 Article 5</div>;
export const contracts_detail_5 = (p:any)=> <div>contracts 5 Article 7</div>;
export const contracts_detail_6 = (p:any)=> <div>contracts 6 Article 12</div>;
export const contracts_detail_7 = (p:any)=> <div>contracts 7 Appendix A</div>;
export const contracts_detail_8 = (p:any)=> <div>contracts 8 Article 5</div>;
export const contracts_detail_9 = (p:any)=> <div>contracts 9 Article 7</div>;
export const contracts_detail_10 = (p:any)=> <div>contracts 10 Article 12</div>;
export const contracts_detail_11 = (p:any)=> <div>contracts 11 Appendix A</div>;
export const contracts_detail_12 = (p:any)=> <div>contracts 12 Article 5</div>;
export const contracts_detail_13 = (p:any)=> <div>contracts 13 Article 7</div>;
export const contracts_detail_14 = (p:any)=> <div>contracts 14 Article 12</div>;
export const contracts_detail_15 = (p:any)=> <div>contracts 15 Appendix A</div>;
export const contracts_detail_16 = (p:any)=> <div>contracts 16 Article 5</div>;
export const contracts_detail_17 = (p:any)=> <div>contracts 17 Article 7</div>;
export const contracts_detail_18 = (p:any)=> <div>contracts 18 Article 12</div>;
export const contracts_detail_19 = (p:any)=> <div>contracts 19 Appendix A</div>;