import React from 'react';
export const workforceDetails = () => <div>workforce distinct</div>;
export const workforce_detail_0 = (p:any)=> <div>workforce 0 employees</div>;
export const workforce_detail_1 = (p:any)=> <div>workforce 1 classifications</div>;
export const workforce_detail_2 = (p:any)=> <div>workforce 2 seniority lists</div>;
export const workforce_detail_3 = (p:any)=> <div>workforce 3 roster</div>;
export const workforce_detail_4 = (p:any)=> <div>workforce 4 employees</div>;
export const workforce_detail_5 = (p:any)=> <div>workforce 5 classifications</div>;
export const workforce_detail_6 = (p:any)=> <div>workforce 6 seniority lists</div>;
export const workforce_detail_7 = (p:any)=> <div>workforce 7 roster</div>;
export const workforce_detail_8 = (p:any)=> <div>workforce 8 employees</div>;
export const workforce_detail_9 = (p:any)=> <div>workforce 9 classifications</div>;
export const workforce_detail_10 = (p:any)=> <div>workforce 10 seniority lists</div>;
export const workforce_detail_11 = (p:any)=> <div>workforce 11 roster</div>;
export const workforce_detail_12 = (p:any)=> <div>workforce 12 employees</div>;
export const workforce_detail_13 = (p:any)=> <div>workforce 13 classifications</div>;
export const workforce_detail_14 = (p:any)=> <div>workforce 14 seniority lists</div>;
export const workforce_detail_15 = (p:any)=> <div>workforce 15 roster</div>;
export const workforce_detail_16 = (p:any)=> <div>workforce 16 employees</div>;
export const workforce_detail_17 = (p:any)=> <div>workforce 17 classifications</div>;
export const workforce_detail_18 = (p:any)=> <div>workforce 18 seniority lists</div>;
export const workforce_detail_19 = (p:any)=> <div>workforce 19 roster</div>;