import React from 'react';
export const payrollDetails = () => <div>payroll distinct</div>;
export const payroll_detail_0 = (p:any)=> <div>payroll 0 wage scales</div>;
export const payroll_detail_1 = (p:any)=> <div>payroll 1 premiums</div>;
export const payroll_detail_2 = (p:any)=> <div>payroll 2 differentials</div>;
export const payroll_detail_3 = (p:any)=> <div>payroll 3 overtime</div>;
export const payroll_detail_4 = (p:any)=> <div>payroll 4 wage scales</div>;
export const payroll_detail_5 = (p:any)=> <div>payroll 5 premiums</div>;
export const payroll_detail_6 = (p:any)=> <div>payroll 6 differentials</div>;
export const payroll_detail_7 = (p:any)=> <div>payroll 7 overtime</div>;
export const payroll_detail_8 = (p:any)=> <div>payroll 8 wage scales</div>;
export const payroll_detail_9 = (p:any)=> <div>payroll 9 premiums</div>;
export const payroll_detail_10 = (p:any)=> <div>payroll 10 differentials</div>;
export const payroll_detail_11 = (p:any)=> <div>payroll 11 overtime</div>;
export const payroll_detail_12 = (p:any)=> <div>payroll 12 wage scales</div>;
export const payroll_detail_13 = (p:any)=> <div>payroll 13 premiums</div>;
export const payroll_detail_14 = (p:any)=> <div>payroll 14 differentials</div>;
export const payroll_detail_15 = (p:any)=> <div>payroll 15 overtime</div>;
export const payroll_detail_16 = (p:any)=> <div>payroll 16 wage scales</div>;
export const payroll_detail_17 = (p:any)=> <div>payroll 17 premiums</div>;
export const payroll_detail_18 = (p:any)=> <div>payroll 18 differentials</div>;
export const payroll_detail_19 = (p:any)=> <div>payroll 19 overtime</div>;