import React from 'react';
export const frontendDetails = () => <div>frontend distinct</div>;
export const frontend_detail_0 = (p:any)=> <div>frontend 0 contract viewer</div>;
export const frontend_detail_1 = (p:any)=> <div>frontend 1 grievance tracker</div>;
export const frontend_detail_2 = (p:any)=> <div>frontend 2 seniority board</div>;
export const frontend_detail_3 = (p:any)=> <div>frontend 3 contract viewer</div>;
export const frontend_detail_4 = (p:any)=> <div>frontend 4 grievance tracker</div>;
export const frontend_detail_5 = (p:any)=> <div>frontend 5 seniority board</div>;
export const frontend_detail_6 = (p:any)=> <div>frontend 6 contract viewer</div>;
export const frontend_detail_7 = (p:any)=> <div>frontend 7 grievance tracker</div>;
export const frontend_detail_8 = (p:any)=> <div>frontend 8 seniority board</div>;
export const frontend_detail_9 = (p:any)=> <div>frontend 9 contract viewer</div>;
export const frontend_detail_10 = (p:any)=> <div>frontend 10 grievance tracker</div>;
export const frontend_detail_11 = (p:any)=> <div>frontend 11 seniority board</div>;
export const frontend_detail_12 = (p:any)=> <div>frontend 12 contract viewer</div>;
export const frontend_detail_13 = (p:any)=> <div>frontend 13 grievance tracker</div>;
export const frontend_detail_14 = (p:any)=> <div>frontend 14 seniority board</div>;
export const frontend_detail_15 = (p:any)=> <div>frontend 15 contract viewer</div>;
export const frontend_detail_16 = (p:any)=> <div>frontend 16 grievance tracker</div>;
export const frontend_detail_17 = (p:any)=> <div>frontend 17 seniority board</div>;
export const frontend_detail_18 = (p:any)=> <div>frontend 18 contract viewer</div>;
export const frontend_detail_19 = (p:any)=> <div>frontend 19 grievance tracker</div>;