import React from 'react';
export const rules_engineDetails = () => <div>rules_engine distinct</div>;
export const rules_engine_detail_0 = (p:any)=> <div>rules_engine 0 violation detection</div>;
export const rules_engine_detail_1 = (p:any)=> <div>rules_engine 1 explainable</div>;
export const rules_engine_detail_2 = (p:any)=> <div>rules_engine 2 audit</div>;
export const rules_engine_detail_3 = (p:any)=> <div>rules_engine 3 remedy</div>;
export const rules_engine_detail_4 = (p:any)=> <div>rules_engine 4 violation detection</div>;
export const rules_engine_detail_5 = (p:any)=> <div>rules_engine 5 explainable</div>;
export const rules_engine_detail_6 = (p:any)=> <div>rules_engine 6 audit</div>;
export const rules_engine_detail_7 = (p:any)=> <div>rules_engine 7 remedy</div>;
export const rules_engine_detail_8 = (p:any)=> <div>rules_engine 8 violation detection</div>;
export const rules_engine_detail_9 = (p:any)=> <div>rules_engine 9 explainable</div>;
export const rules_engine_detail_10 = (p:any)=> <div>rules_engine 10 audit</div>;
export const rules_engine_detail_11 = (p:any)=> <div>rules_engine 11 remedy</div>;
export const rules_engine_detail_12 = (p:any)=> <div>rules_engine 12 violation detection</div>;
export const rules_engine_detail_13 = (p:any)=> <div>rules_engine 13 explainable</div>;
export const rules_engine_detail_14 = (p:any)=> <div>rules_engine 14 audit</div>;
export const rules_engine_detail_15 = (p:any)=> <div>rules_engine 15 remedy</div>;
export const rules_engine_detail_16 = (p:any)=> <div>rules_engine 16 violation detection</div>;
export const rules_engine_detail_17 = (p:any)=> <div>rules_engine 17 explainable</div>;
export const rules_engine_detail_18 = (p:any)=> <div>rules_engine 18 audit</div>;
export const rules_engine_detail_19 = (p:any)=> <div>rules_engine 19 remedy</div>;