import React from 'react';
export const documentsDetails = () => <div>documents distinct</div>;
export const documents_detail_0 = (p:any)=> <div>documents 0 CBA PDFs</div>;
export const documents_detail_1 = (p:any)=> <div>documents 1 MOUs</div>;
export const documents_detail_2 = (p:any)=> <div>documents 2 side letters</div>;
export const documents_detail_3 = (p:any)=> <div>documents 3 amendments</div>;
export const documents_detail_4 = (p:any)=> <div>documents 4 CBA PDFs</div>;
export const documents_detail_5 = (p:any)=> <div>documents 5 MOUs</div>;
export const documents_detail_6 = (p:any)=> <div>documents 6 side letters</div>;
export const documents_detail_7 = (p:any)=> <div>documents 7 amendments</div>;
export const documents_detail_8 = (p:any)=> <div>documents 8 CBA PDFs</div>;
export const documents_detail_9 = (p:any)=> <div>documents 9 MOUs</div>;
export const documents_detail_10 = (p:any)=> <div>documents 10 side letters</div>;
export const documents_detail_11 = (p:any)=> <div>documents 11 amendments</div>;
export const documents_detail_12 = (p:any)=> <div>documents 12 CBA PDFs</div>;
export const documents_detail_13 = (p:any)=> <div>documents 13 MOUs</div>;
export const documents_detail_14 = (p:any)=> <div>documents 14 side letters</div>;
export const documents_detail_15 = (p:any)=> <div>documents 15 amendments</div>;
export const documents_detail_16 = (p:any)=> <div>documents 16 CBA PDFs</div>;
export const documents_detail_17 = (p:any)=> <div>documents 17 MOUs</div>;
export const documents_detail_18 = (p:any)=> <div>documents 18 side letters</div>;
export const documents_detail_19 = (p:any)=> <div>documents 19 amendments</div>;