import React from 'react';
export const schedulingDetails = () => <div>scheduling distinct</div>;
export const scheduling_detail_0 = (p:any)=> <div>scheduling 0 shift assignment</div>;
export const scheduling_detail_1 = (p:any)=> <div>scheduling 1 overtime</div>;
export const scheduling_detail_2 = (p:any)=> <div>scheduling 2 bidding</div>;
export const scheduling_detail_3 = (p:any)=> <div>scheduling 3 premium</div>;
export const scheduling_detail_4 = (p:any)=> <div>scheduling 4 shift assignment</div>;
export const scheduling_detail_5 = (p:any)=> <div>scheduling 5 overtime</div>;
export const scheduling_detail_6 = (p:any)=> <div>scheduling 6 bidding</div>;
export const scheduling_detail_7 = (p:any)=> <div>scheduling 7 premium</div>;
export const scheduling_detail_8 = (p:any)=> <div>scheduling 8 shift assignment</div>;
export const scheduling_detail_9 = (p:any)=> <div>scheduling 9 overtime</div>;
export const scheduling_detail_10 = (p:any)=> <div>scheduling 10 bidding</div>;
export const scheduling_detail_11 = (p:any)=> <div>scheduling 11 premium</div>;
export const scheduling_detail_12 = (p:any)=> <div>scheduling 12 shift assignment</div>;
export const scheduling_detail_13 = (p:any)=> <div>scheduling 13 overtime</div>;
export const scheduling_detail_14 = (p:any)=> <div>scheduling 14 bidding</div>;
export const scheduling_detail_15 = (p:any)=> <div>scheduling 15 premium</div>;
export const scheduling_detail_16 = (p:any)=> <div>scheduling 16 shift assignment</div>;
export const scheduling_detail_17 = (p:any)=> <div>scheduling 17 overtime</div>;
export const scheduling_detail_18 = (p:any)=> <div>scheduling 18 bidding</div>;
export const scheduling_detail_19 = (p:any)=> <div>scheduling 19 premium</div>;